### ISSUE TITLE
Consider contributing to devnull42 repository?

### ISSUE THREAD

**Issue by olebole** [wjoye/taccle#1]
Dear William,

since in saods9 version 8, taccle (and fickle) are needed to build the package from source (and I don't want to include these as part of the ds9 source in Debian), I think about separately packaging taccle and fickle.

I think that your changes to the original version are worth to be discussed with the original author, @devnull42. Would you consider creating a pull request there? If it gets merged, I could use his repository to create a Debian package, which then would be a build dependency for saods9.

I already went through the changes, rebased them to [devnull42/taccle](https://github.com/devnull42/taccle), and created a sample PR in my own fork: olebole/taccle#1 . If you don't like to do it yourself, would you mind if I do?

Best regards

Ole

@devnull42: would you still consider such patches, or is taccle development stopped completely?

**Comment by wjoye** [comment]
Ole

I’m not sure what to do about my versions of taccle and fickle. As you have noticed the modifications to both, I considered them to be a derived work. Some of the changes may be of use to others, but I’m afraid to say I’ve hack a few features into them that are not ready for prime time. I was under the impression that they have been orphaned, but I could be wrong. Lets see if we get any response from the authors and proceed from there. In the mean time please distribute as packaged. Things would be really screwed up if the original versions where used.

bill

**Comment by wjoye** [comment]
Ole

One other note: I do maintain a separate repository of all the works I’ve acquired and modified for use in DS9:

https://github.com/wjoye?tab=repositories

Most of these have been orphaned and I’ve brought them up to date for use with tcl/tk 8.6, along with a few bug fixes and enhancements. I do maintain these repositories as I use a subtree from these into the DS9 repository. So as changes are made, they are reflected here. And the versions numbers are active.

bill

**Comment by olebole** [comment]
@wjoye, I am also not sure what to do. I just want to avoid fragmentation. For the moment I include taccle and fickle in the saods9 package (which I just uploaded to experimental), but if the changes are general and  @devnull42 is still active here, I would prefer a common solution. If not, I am fine with using a private variant (neither taccle nor fickle are in Debian yet anyway).

> I do maintain a separate repository of all the works I’ve acquired and modified for use in DS9

I know; some of the packages are taken from there (f.e. tkblt). Your work is really great and helps a lot to understand the ds9 structure and to adjust it to our policy. Thanks!

**Comment by devnull42** [comment]
I would consider the work orphaned -- I wrote the original tools for a college course. You are welcome to adopt the utilities.
