### ISSUE TITLE
possible comparison bug

### ISSUE THREAD

**Issue by cshorler** [wjoye/taccle#2]
what's the intended use of yycnt

https://github.com/wjoye/taccle/blob/master/taccle.tcl#L952

if $token is a string literal less than 0 e.g. "/", I'm not sure this is the intended effect - but then yycnt doesn't appear to be used anyway?

**Comment by wjoye** [comment]
yycnt is an undocumented feature which allows the user to determine how many tokens were actually processed after the parser returns. For example, if you have a very long command line, a loop can invoke the parser, processing just one part of the command line at a time.

**Comment by cshorler** [comment]
fair enough, I was pointing out that I don't think the token count will be correct for certain character literals (where there is no token value from the taccle tab file)

This was my contrived example
```
% set yyindex 3
3
% set yybuf "abc/def"
abc/def
% set yyindex 3
3
% set yytext [string range $yybuf $yyindex $yyindex] 
/
% expr {$yytext > 0}
0
```
